Upcoming sakhite
Aura-healthcare/seizure_detection_pipeline pull request #9
Opened 2022-06-30 09:45 UTC by infini11

2022-06-30 12:52 UTC, al1032735 commented on src/usecase/feature_engineering.py
> +    dataframe_clean: pd.DataFrame = dataframe_origine.copy()
Pourquoi tu fais une `copy`? 

```python
  dataframe_clean = dataframe_clean.sort_values(by='timestamp').reset_index(drop=True)
    dataframe_clean.drop(col_to_drop, axis=1, inplace=True)
```

Ca fait deja une copie ça non ?

2022-06-30 13:34 UTC, al1032735 commented on data/test_data/test_data_feat_eng.csv
> +mean_hr,sdsd,lf,hf,set,timestamp,label
Bon c'est pas un gros fichier mais c'est typiquement, le type de fichier que l'on pourrait stocker comme un artefact dans un repo de données.

2022-06-30 13:34 UTC, al1032735 commented on src/usecase/feature_engineering.py
> +    outlier_score = pd.DataFrame()
Tu n'es pas obligé d'instancier une nouvelle dataframe vide. Surtout que, ensuite, tu ne stockes pas un objet dataframe dedans.

2022-06-30 13:34 UTC, al1032735 commented on src/usecase/feature_engineering.py
> +def createContextualFeatues(dataframe: pd.DataFrame) -> pd.DataFrame:
Ta méthode est un peu longue, je la découperais

2022-06-30 13:34 UTC, al1032735 commented on src/usecase/feature_engineering.py
> +    if path == 'output/feats-v0_6/feats_EEG_297_s1.csv':
Ce serait peut-être intéressant de mettre ca dans une variable globale

2022-06-30 13:34 UTC, al1032735 commented on src/usecase/feature_engineering.py
> +        return 12
Pourquoi 12 ? Je créerai une variable globale aussi avec un nom plus pertinent

2022-06-30 13:34 UTC, al1032735 commented on src/usecase/train_model.py
>  def train_model(ml_dataset_path: str,
Je suis pas fan de tes `.copy()`

2022-06-30 13:34 UTC, al1032735 commented on src/usecase/train_model.py
> +                X_train = df_ml.\
Tu le fais deux fois ça, tu devrais extraire dans une méthode

2022-06-30 13:34 UTC, al1032735 commented on src/usecase/train_model.py
> +                    X, y, test_size=0.3, random_state=42, stratify=y)
Ce serait peut-être mieux de variabiliser ces "magic values". Plus compréhensible et automatisable.

2022-06-30 13:34 UTC, al1032735 commented on tests/test_src_usecase/test_feature_engineering.py
> +def test_replace_infinite_values_by_nan(dataframe):
Et ça je le variabiliserai dans le `#When` plutôt que de faire la modif dans le `#Then`

2022-06-30 13:34 UTC, al1032735 commented on tests/test_src_usecase/test_feature_engineering.py
> +    assert dataframe.isin([np.inf, -np.inf]).values.any() != expected_response
Comme au dessus

2022-06-30 13:34 UTC, al1032735 commented on tests/test_src_usecase/test_feature_engineering.py
> +    assert dataframe_imputed.isna().values.any() != expected_response
Comme au-dessus

2022-06-30 13:34 UTC, al1032735 commented on tests/test_src_usecase/test_feature_engineering.py
> +    assert dataframe_imputed.isna().values.any() == expected_response
Bon tu feras la modif dans les méthodes ou c'est aussi comme ça

2022-06-30 13:34 UTC, al1032735 commented on tests/test_src_usecase/test_feature_engineering.py
> +    col_to_drop = ['timestamp', 'set']
Tu le remets dans plusieurs tests >> variable

2022-07-04 09:20 UTC, infini11 commented on src/usecase/feature_engineering.py
> +    dataframe_clean: pd.DataFrame = dataframe_origine.copy()
Je veux garder le dataframe origine, sinon toute modification faite sur le copy se répercute sur l'origine.

2022-07-04 09:20 UTC, infini11 commented on src/usecase/feature_engineering.py
> +    filt = outlier_score["score"] < -1.5
Daccord, fait !!

2022-07-04 09:21 UTC, infini11 commented on src/usecase/feature_engineering.py
> +    dataframe = zscore(dataframe)
Sur ce cas, Oui. Mais je pense on peut le sortir pour les autres utilisations

2022-07-04 09:22 UTC, infini11 commented on data/test_data/test_data_feat_eng.csv
> +mean_hr,sdsd,lf,hf,set,timestamp,label
D'accord

2022-07-04 09:23 UTC, infini11 commented on tests/test_src_usecase/test_feature_engineering.py
> +    assert dataframe_imputed.isna().values.any() != expected_response
J'ai pas compris aussi

2022-07-04 09:25 UTC, infini11 commented on tests/test_src_usecase/test_feature_engineering.py
> +    assert dataframe_imputed.isna().values.any() == expected_response
Après avoir imputé le dataframe, normalement on doit plus avoir de valeurs manquantes : donc je vérifie si on a des nan ou pas.

2022-07-04 09:27 UTC, infini11 commented on tests/test_src_usecase/test_feature_engineering.py
> +    col_to_drop = ['timestamp', 'set']
Oui c'est juste arbitraire, je pouvais changer le nom des colonnes aussi. Vu que dans le dataframe y a des colonnes à supprimer, j'ai pris ça en compte sur la méthode get_dataset

2022-07-12 16:54 UTC, LeaNac requested changes

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +    filt = outlier_score["score"] < -1.5
Expliquer en commentaire, quelque part (dans le fichier de conf) d'où vient cette valeur -1.5

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +    pca_out = pca.fit(dataframe)
pca_trained à la place ?

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +
tu peux faire un > black sur ton code, pour tout bien reformater ;)

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +
(saut de ligne en trop)

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +    new_size_dataset = pca_out.components_.shape[1]
number_of_variables tu veux dire ?

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +        list_colmuns.append("PC"+str(i))
Tu peux faire une liste compréhension à la place (plus rapide qu'une boucle for) : 
["PC"+str(i) for i in range(1,nb_of_variables)]

un peu de lecture : https://python.doctor/page-comprehension-list-listes-python-cours-debutants ;)

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +    # dataframe['second'] = dataframe.timestamp.dt.second
enlever le code pas utilisé (pas de "dead code")

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +        dataframe['sd2_%s'%(period)] = dataframe['sd2'].rolling(window=period, min_periods=10).mean()
j'extrairais ça dans une fonction avec "period" comme input, et je mettrais l'utilisation de cette fonction dans une liste compréhension. T'en penses quoi ? 
A la place de la boucle for 
[fonction(period) for period in list_periods]

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +    # dataframe['second'] = dataframe.timestamp.dt.second
extraire ce bloque aussi dans une fonction : _compute_time_features_

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +    return dataframe.fillna(-999)
-999 : magic number ?

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/feature_engineering.py
> +        return 12
magic number 🧐

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
>  MLRUNS_DIR = f'{os.getcwd()}/mlruns'
à mettre dans le fichier de conf

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
> +    df_ml = df_ml.fillna(-999)
magic number 🧐

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
> +    df_ml = df_ml.fillna(-999)
mettre ce nombre en variable globale dans le fichier de conf, en lui donnant un nom explicite (important)

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
> +def plot_feature_importance(importance: np.array, feat_names: list, model_type: str, mlruns_dir: str) -> None:
je la mettrais dans un autre fichier : _visualization.py_ par exemple

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
>  def train_model(ml_dataset_path: str,
je la renommerais : _training_pipeline_ parce que tu fais plus que juste entrainer ton modèle, tu récupères tes données, les nettoies ... et je garderais l'entrainement du modèle, vraiment dans une fonction spécifique, avec les données traitées

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
> +                X_train = df_ml.\
je suis d'acc, ta fonction est trop longue. On s'y perd un peu. Je mettrais les deux blocs de .drop dans une fonction

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
> +                df_ml_test = df_ml_test_copy[df_ml_test_copy['patient_id']==50]
magic_number 🧐 mettre le 50 dans une variable globale (dans conf) 
ou en input de ta fonction

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
> +            # X, y = ros.fit_resample(X_train, y_train)
dead code ? si oui à supprimer

2022-07-12 16:54 UTC, LeaNac commented on src/usecase/train_model.py
> +            # mlflow.log_param('algorith', 'rfc')
elle est là ta fonction : _train_model_

2022-07-12 16:54 UTC, LeaNac commented on tests/test_src_usecase/test_feature_engineering.py
> +DATASET_FILE_PATH_FEAT = "data/test_data/test_data_feat_contextual.csv"
à mettre dans le fichier de conf

2022-07-18 10:06 UTC, infini11 commented on src/usecase/feature_engineering.py
> +    filt = outlier_score["score"] < -1.5
D'accord !

2022-07-18 10:08 UTC, infini11 commented on data/test_data/test_data_feat_eng.csv
> +mean_hr,sdsd,lf,hf,set,timestamp,label
C'est pour moi la question ? (j'ai utilisé ce fichier pour tester les fonctionnalités de feature engineering).

2022-07-18 10:10 UTC, infini11 commented on src/usecase/feature_engineering.py
> +    dataframe_clean: pd.DataFrame = dataframe_origine.copy()
Oui oui pourquoi pas !

2022-07-18 10:11 UTC, infini11 commented on src/usecase/feature_engineering.py
> +    dataframe_clean = dataframe_clean.sort_values(by='timestamp').reset_index(drop=True)
D'accord, c'est noté !

2022-07-18 10:11 UTC, infini11 commented on src/usecase/feature_engineering.py
> +    dataframe_clean.drop(col_to_drop, axis=1, inplace=True)
D'accord, c'est noté !

2022-07-18 10:15 UTC, infini11 commented on src/usecase/train_model.py
> +            # X, y = ros.fit_resample(X_train, y_train)
Pas vraiment, je l'utilise avec le model random forest. Après, je voulais pas perdre l'ordre dans les données, c'est pour cela que je l'ai commenté!

2022-07-18 10:18 UTC, infini11 commented on src/usecase/train_model.py
> +            # mlflow.log_param('algorith', 'rfc')
Oui je comprends. Le code à évoluer avec l'inclusion de la fonctionnalité orchestration (et donc j'ai encapsulé cette partie dans une fonction train)

2022-07-18 10:18 UTC, infini11 commented on tests/test_src_usecase/test_feature_engineering.py
> +DATASET_FILE_PATH_FEAT = "data/test_data/test_data_feat_contextual.csv"
D'accord !

2022-07-18 11:23 UTC, infini11 commented on src/usecase/feature_engineering.py
> +        return 12
C'est un cas spécifique, dû à une erreur d'extraction. C'est pour cela que j'ai adapté le code en attendant qu'Aléxis gère ça.

2022-07-18 11:23 UTC, infini11 commented on src/usecase/train_model.py
>  def train_model(ml_dataset_path: str,
D'accord !

2022-07-18 11:24 UTC, infini11 commented on tests/test_src_usecase/test_feature_engineering.py
> +def test_replace_infinite_values_by_nan(dataframe):
D'accord !

2024-09-26 19:17 UTC, merged